[build]
  command = """
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
    export PYENV_ROOT="$HOME/.pyenv" && \
    export PATH="$PYENV_ROOT/bin:$PATH" && \
    eval "$(pyenv init -)" && \
    pyenv install 3.10.12 && \
    pyenv global 3.10.12 && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    poetry config virtualenvs.create false && \
    npm run build
  """
  publish = "build"

[build.environment]
  NODE_VERSION = "16.17.0"

[build.processing]
  skip_processing = false
